# Generated by Django 3.1.7 on 2021-03-30 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QtechApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchhistory',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 17, 12, 14, 171052), verbose_name='date created'),
        ),
    ]
