# Generated by Django 3.1.7 on 2021-03-30 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QtechApps', '0002_auto_20210330_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchhistory',
            name='createdTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
